### ISSUE TITLE
Falcon::PreventionPoliciesApi#get_prevention_policies fails with HTTP status code: 400 -  Missing required query string parameter 'ids'

### ISSUE THREAD

**Issue by hiboma** [CrowdStrike/crimson-falcon#26]
Hello. I was looking to use CrowdStrike Falcon's API in Ruby and was happy to find this repository.
I immediately tried using this gem, but encountered unintended behavior, so I'm opening an issue.

## How to reproduce

---

## code

```ruby
#!/usr/bin/env ruby

require 'dotenv'
require 'crimson-falcon'

# set FALCON_CLIENT_ID, FALCON_CLIENT_SECRET
Dotenv.load

Falcon.configure do |config|
  config.client_id     = ENV["FALCON_CLIENT_ID"]
  config.client_secret = ENV["FALCON_CLIENT_SECRET"]
end

client = Falcon::PreventionPoliciesApi.new

# ok
result = client.query_prevention_policies({})

# I made sure the ids was not empty
ids = result.resources

# raise!
result = client.get_prevention_policies(ids)
```

### result

```markdown
/tmp/falcon $ bundle exec ruby main.rb
/private/tmp/falcon/vendor/bundle/ruby/3.2.0/gems/crimson-falcon-0.3.0/lib/crimson-falcon/api_client.rb:191:in `raise_error': Error message: the server returns an error (Falcon::ApiError)
HTTP status code: 400
Response headers: {"Server"=>"nginx", "Date"=>"Tue, 12 Sep 2023 11:10:45 GMT", "Content-Type"=>"application/json", "Content-Length"=>"202", "Connection"=>"keep-alive", "Strict-Transport-Security"=>["max-age=15724800; includeSubDomains", "max-age=31536000; includeSubDomains"], "X-Cs-Region"=>"us-1", "X-Cs-Traceid"=>"8f5eff88-a41c-4d99-90fe-ce25989a4826", "X-Ratelimit-Limit"=>"6000", "X-Ratelimit-Remaining"=>"5998"}
Response body: {
 "meta": {
  "query_time": 0.000204423,
  "trace_id": "8f5eff88-a41c-4d99-90fe-ce25989a4826"
 },
 "errors": [
  {
   "code": 400,
   "message": "Missing required query string parameter 'ids'"
  }
 ]
}
	from /private/tmp/falcon/vendor/bundle/ruby/3.2.0/gems/crimson-falcon-0.3.0/lib/crimson-falcon/api_client.rb:88:in `call_api'
	from /private/tmp/falcon/vendor/bundle/ruby/3.2.0/gems/crimson-falcon-0.3.0/lib/crimson-falcon/api/prevention_policies_api.rb:222:in `get_prevention_policies_with_http_info'
	from /private/tmp/falcon/vendor/bundle/ruby/3.2.0/gems/crimson-falcon-0.3.0/lib/crimson-falcon/api/prevention_policies_api.rb:172:in `get_prevention_policies'
	from main.rb:20:in `<main>'
```

## gem version

```
0.3.0
```

## ruby version

```markdown
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]
```

**Comment by hiboma** [comment]
I have verified that the following code passing id as String to get_prevention_policies returns 200 OK.

```ruby
#!/usr/bin/env ruby

require 'dotenv'
require 'crimson-falcon'

# set FALCON_CLIENT_ID, FALCON_CLIENT_SECRET

Dotenv.load

Falcon.configure do |config|
config.client_id     = ENV["FALCON_CLIENT_ID"]
config.client_secret = ENV["FALCON_CLIENT_SECRET"]
end

client = Falcon::PreventionPoliciesApi.new
client.api_client.config.debugging = true

ids = "262726297f7f4c2faffd4d0acd5e0079"

client.get_prevention_policies(ids)
```

```markdown
$ bundle exec ruby main.rb
D, [2023-09-12T20:32:22.662010 #77564] DEBUG -- : Calling API: PreventionPoliciesApi.get_prevention_policies ...
{:method=>:get, :headers=>{"Content-Type"=>"application/json", "User-Agent"=>"crowdstrike-crimson/0.3.0", "Accept"=>"application/json", "Authorization"=>"Bearer ***"}, :params=>{:ids=>"262726297f7f4c2faffd4d0acd5e0079"}, :params_encoding=>nil, :timeout=>0, :ssl_verifypeer=>true, :ssl_verifyhost=>2, :sslcert=>nil, :sslkey=>nil, :verbose=>true, :followlocation=>false}
https://api.crowdstrike.com/policy/entities/prevention/v1
Found bundle for host: 0x60000342dfe0 [serially]
Can not multiplex, even if we wanted to
Re-using existing connection #0 with host [api.crowdstrike.com](http://api.crowdstrike.com/)
GET /policy/entities/prevention/v1?ids=262726297f7f4c2faffd4d0acd5e0079 HTTP/1.1
Host: [api.crowdstrike.com](http://api.crowdstrike.com/)
User-Agent: crowdstrike-crimson/0.3.0
Content-Type: application/json
Accept: application/json
Authorization: Bearer ***

HTTP/1.1 200 OK
Server: nginx
Date: Tue, 12 Sep 2023 11:32:26 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Strict-Transport-Security: max-age=15724800; includeSubDomains
X-Cs-Region: us-1
X-Cs-Traceid: c3998d39-0b84-430f-80ff-52dc280ff718
X-Ratelimit-Limit: 6000
X-Ratelimit-Remaining: 5995
Strict-Transport-Security: max-age=31536000; includeSubDomains

Connection #0 to host [api.crowdstrike.com](http://api.crowdstrike.com/) left intact
D, [2023-09-12T20:32:22.827779 #77564] DEBUG -- : HTTP response body ~BEGIN~

... snip
```

However, passing an Array<String> to get_prevention_policies will result in a 400 Bad Request.

```ruby
#!/usr/bin/env ruby

require 'dotenv'
require 'crimson-falcon'

# set FALCON_CLIENT_ID, FALCON_CLIENT_SECRET
Dotenv.load

Falcon.configure do |config|
  config.client_id     = ENV["FALCON_CLIENT_ID"]
  config.client_secret = ENV["FALCON_CLIENT_SECRET"]
end

client = Falcon::PreventionPoliciesApi.new
client.api_client.config.debugging = true

ids = ["262726297f7f4c2faffd4d0acd5e0079", "262726297f7f4c2faffd4d0acd5e0079"]

client.get_prevention_policies(ids)
```

```
$ bundle exec ruby main.rb
D, [2023-09-12T20:35:28.945239 #77891] DEBUG -- : Calling API: PreventionPoliciesApi.get_prevention_policies ...
{:method=>:get, :headers=>{"Content-Type"=>"application/json", "User-Agent"=>"crowdstrike-crimson/0.3.0", "Accept"=>"application/json", "Authorization"=>"Bearer ***"}, :params=>{:ids=>["262726297f7f4c2faffd4d0acd5e0079", "262726297f7f4c2faffd4d0acd5e0079"]}, :params_encoding=>nil, :timeout=>0, :ssl_verifypeer=>true, :ssl_verifyhost=>2, :sslcert=>nil, :sslkey=>nil, :verbose=>true, :followlocation=>false}
https://api.crowdstrike.com/policy/entities/prevention/v1
Found bundle for host: 0x60000124db00 [serially]
Can not multiplex, even if we wanted to
Re-using existing connection #0 with host api.crowdstrike.com
GET /policy/entities/prevention/v1?ids%5B0%5D=262726297f7f4c2faffd4d0acd5e0079&ids%5B1%5D=262726297f7f4c2faffd4d0acd5e0079 HTTP/1.1
Host: api.crowdstrike.com
User-Agent: crowdstrike-crimson/0.3.0
Content-Type: application/json
Accept: application/json
Authorization: Bearer ***

HTTP/1.1 400 Bad Request
Server: nginx
Date: Tue, 12 Sep 2023 11:35:33 GMT
Content-Type: application/json
Content-Length: 202
Connection: keep-alive
Strict-Transport-Security: max-age=15724800; includeSubDomains
X-Cs-Region: us-1
X-Cs-Traceid: 87020ef2-a9bf-4181-96b9-564d34b2e0ea
X-Ratelimit-Limit: 6000
X-Ratelimit-Remaining: 5999
Strict-Transport-Security: max-age=31536000; includeSubDomains

Connection #0 to host api.crowdstrike.com left intact
D, [2023-09-12T20:35:29.106727 #77891] DEBUG -- : HTTP response body ~BEGIN~
{
 "meta": {
  "query_time": 0.000234094,
  "trace_id": "87020ef2-a9bf-4181-96b9-564d34b2e0ea"
 },
 "errors": [
  {
   "code": 400,
   "message": "Missing required query string parameter 'ids'"
  }
 ]
}
~END~

... snip
```

The debug log shows that query parameters are converted as follows. 

`?ids[0]=262726297f7f4c2faffd4d0acd5e0079&ids[1]=262726297f7f4c2faffd4d0acd5e0079`

I think there is a problem with the handling of `ids`, what do you think?

https://github.com/CrowdStrike/crimson-falcon/blob/main/lib/crimson-falcon/api/prevention_policies_api.rb#L193

**Comment by carlosmmatos** [comment]
@hiboma - I'm sorry for the very late response. Got pulled away into other assignments but looking to revive some life into this. First of all, thank you for opening up this issue! 

Secondly, I think I know the problem with this endpoint. This is one of those poorly documented/configured API endpoints we have that don't make much sense.. but hopefully this will explain the issue:

it's expecting the list of id's to be converted into this:
ids=<id1>&ids=<id2>&ids=<idsN>..

I'm looking into this now to see how to support this.

**Comment by carlosmmatos** [comment]
Okay found the issue. The issue seems to stem from the way the Typhoeus library handles how the params hash. As you noted, by default it will try to pass it in as each item in the array with it's index. I found that the encoding can be updated to a format that doesn't do that and provides us with the correct way. The issue is in this [code](https://github.com/typhoeus/ethon/blob/master/lib/ethon/easy/queryable.rb):

```ruby
      def recursively_generate_pairs(h, prefix, pairs)
        case h
        when Hash
          encode_hash_pairs(h, prefix, pairs)
        when Array
          if params_encoding == :rack
            encode_rack_array_pairs(h, prefix, pairs)
          elsif params_encoding == :multi
            encode_multi_array_pairs(h, prefix, pairs)
          elsif params_encoding == :none
            pairs << [prefix, h]
          else
            encode_indexed_array_pairs(h, prefix, pairs)
          end
        end
      end
```

To test this out, you can update your configuration block on your ruby code to this:

```ruby
Falcon.configure do |config|
  ...
  config.params_encoding = :multi
```

The multi encoding is what we want. What I need to do is figure out how to best accommodate this fix into the codebase as there are about 110 instances in the codebase where we are passing in a similar Array<String> `ids` - so I want to make sure we provide the same fix across the board.
